# Generated by Django 5.0.6 on 2024-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overview',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
